### PR TITLE
Set up automated accessibility testing in the frontend

### PR DESCRIPTION
**Pull request by bryangaledxw**
# Context
This PR adds automated accessibility testing on all integration and e2e tests.

# Changes in this PR
* Introduce `cypress-axe` and `axe-core` dependencies
* Configure rules with defaults from [CAS1](https://github.com/ministryofjustice/hmpps-approved-premises-ui/blob/main/integration_tests/pages/page.ts#L27)
* Address any other accessibility issues

#### Sentence length input
sentence_length_before

#### PDU input
pdu_before

#### Archiving a property flash messages
Screenshot 2023-09-06 at 08 56 28

#### Editing a bedspace that belongs to an archived property
Screenshot 2023-09-06 at 17 02 58 1

#### Sentence length input
sentence_length_after

#### PDU input
pdu_after

#### Archiving a property flash messages
image

#### Editing a bedspace that belongs to an archived property
Screenshot 2023-09-06 at 16 43 15

#### Accessibility failures in the console
a11y_log_multiple
a11ly_log_single

# Release checklist

[Release process documentation](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/edit-v2/4247847062?draftShareId=a1c360ab-bd31-4db1-aae3-7cc002761de9).

## Pre-merge checklist

- [ ] Are any changes required to dependent services for this change to work?
  (eg. CAS API)
- [ ] Have they been released to production already?

## Post-merge checklist

- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to test
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to preprod
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to prod

### CODE REVIEW

**Comment by bryangaledxw** [comment]
[Set up automated accessibility testing in the frontend](https://trello.com/c/GpU3kNpT/1286-set-up-automated-accessibility-testing-in-the-frontend)

**Comment by libuk** [comment]
This is really helpful, thanks!

**Comment by bryangaledxw** [comment]
I'm confused about the warning that `cypress-axe` should be a dependency, rather than a devDependency, as CAS1 have it working as a devDependency.

We're doing `import 'cypress-axe'` in `page.ts`, rather than `integration_tests/support/index.ts` as CAS1 does. But that doesn't seem to work on CAS3, as webpack then gives errors when building the integration tests. I'm not sure what we're doing differently to CAS1 to cause that.

**Review by pezholio — APPROVED** [review]
LGTM - like the way you've added guidance in the commit messages too 🙏

**Comment by selina-dxw** [comment]
Looks good, thanks!

**Pull request merged**
