### PR TITLE
Fix application submission journey

### PR DESCRIPTION
**Pull request by bryangaledxw**
# Changes in this PR

The PR addresses several issues around application submission

* The "confirm" check box and submit button no longer appear until the user has completed all tasks in the application
* If the "confirm" check box is not checked, and the user clicks submit, an error is show, and the task list no longer disappears
* If the user changes their answers after completing "Check Your Answers", they must go through CYA again

### Before
localhost_3000_applications_8a58f76c-5d68-4d37-b165-a0f91c543b9e
localhost_3000_applications_8a58f76c-5d68-4d37-b165-a0f91c543b9e_submission

### After
localhost_3000_applications_cf0e441e-4f4a-4a79-9f93-70054636a91e
localhost_3000_applications_cf0e441e-4f4a-4a79-9f93-70054636a91e (1)
localhost_3000_applications_cf0e441e-4f4a-4a79-9f93-70054636a91e (2)

# Release checklist

[Release process documentation](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/edit-v2/4247847062?draftShareId=a1c360ab-bd31-4db1-aae3-7cc002761de9).

## Pre-merge checklist

- [ ] Are any changes required to dependent services for this change to work?
  (eg. CAS API)
- [ ] Have they been released to production already?

## Post-merge checklist

- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to test
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to preprod
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to prod

### CODE REVIEW

**Comment by bryangaledxw** [comment]
[Fix application submission journey](https://trello.com/c/xIJT3dk2/1269-fix-application-submission-journey)

**Comment by selina-dxw** [comment]
Looks good, thanks

**Review by Harriethw — APPROVED** [review]
LGTM - think we will need to follow a similar pattern in CAS2.
I wasn't able to see how to make an application when running locally though, is there a role that needs to be added to a user to be able to refer?

**Comment by bryangaledxw** [comment]
@Harriethw Thanks! Yep, you probably need something like this - https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/742

**Comment by bryangaledxw** [comment]
@Harriethw Looking at this again I think I misunderstood your question. Applications in CAS3 aren't wired up to the dashboard yet, you need to manually navigate to `localhost:3000/applications`

**Pull request merged**
