### PR TITLE
Introduce PoP phone number field to application

### PR DESCRIPTION
**Pull request by libuk**
# Context
We want to record the PoP's (person on probation) phone number in the
contact details section of the application.

This is an optional field and should not produce errors if it is not supplied.

# Changes in this PR

## Screenshots of UI changes
Screenshot 2023-11-13 at 15 44 54

Screenshot 2023-11-13 at 12 08 43

# Release checklist

[Release process documentation](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/edit-v2/4247847062?draftShareId=a1c360ab-bd31-4db1-aae3-7cc002761de9).

## Pre-merge checklist

- [ ] Are any changes required to dependent services for this change to work?
  (eg. CAS API)
- [ ] Have they been released to production already?

## Post-merge checklist

- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to test
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to preprod
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to prod

### CODE REVIEW

**Comment by libuk** [comment]
[Add a phone number for PoP](https://trello.com/c/ooh2K2DL/1664-add-a-phone-number-for-pop)

**Review by tahb — COMMENTED** [review]
Do we know what will happen to in progress referrals who've completed this section but haven't yet submitted when this change is released? [I've dug up what we did this before](https://github.com/ministryofjustice/hmpps-temporary-accommodation-ui/pull/524/commits/b661f9754e6a44f016d201068f85356fb7c39efc) and it seems like something we should implement here to me, what do you think?

**Comment by tahb** [comment]
Oh I hadn't spotted that this is a new page (rather than merging into an existing page) so it should appear as a new incomplete question out of the box right? Meaning any in progress referral can easily see what they need to go back and add?

**Comment by libuk** [comment]
@tahb 

> Oh I hadn't spotted that this is a new page (rather than merging into an existing page) so it should appear as a new incomplete question out of the box right? Meaning any in progress referral can easily see what they need to go back and add?

As it's an optional field I believe in-progress applications will be free to submit without completing this question. This is because we check for any [page errors just before we submit](https://github.com/ministryofjustice/hmpps-temporary-accommodation-ui/blob/feature/1664-add-pop-phone-number-to-form/server/utils/applicationUtils.ts#L119).

As it's optional, [we don't include an error](https://github.com/ministryofjustice/hmpps-temporary-accommodation-ui/blob/6e1f5c39ee680a40c3775e3378882fb1b79e1f80/server/form-pages/apply/accommodation-need/contact-details/popPhoneNumber.ts#L35) if it's not supplied.

**Review by tahb — APPROVED** [review]

**Comment by libuk** [comment]
@tahb 

Actually, you're right, it will require you to go back and complete the section. The UX is a little iffy as it looks like you've lost progress, but I've confirmed it does work.

https://github.com/ministryofjustice/hmpps-temporary-accommodation-ui/assets/6377078/355d775d-73a4-4b51-980b-cabee4f68bf1

**Pull request merged**
