### PR TITLE
Remaining sentence info pages

### PR DESCRIPTION
**Pull request by bryangaledxw**
# Changes in this PR

* Changes to sentence type page
* Additional offending summary and sentence length pages

### Before
localhost_3000_applications_840b47aa-4a6e-4f61-8929-6ca683d3367c_tasks_sentence-information_pages_sentence-type

#### Offending summary
localhost_3000_applications_7dcfc141-6e9c-443f-9c63-ef6daa5f2ff7_tasks_sentence-information_pages_offending-summary
localhost_3000_applications_7dcfc141-6e9c-443f-9c63-ef6daa5f2ff7_tasks_sentence-information_pages_offending-summary (1)

#### Setence type
localhost_3000_applications_7dcfc141-6e9c-443f-9c63-ef6daa5f2ff7_tasks_sentence-information_pages_sentence-type

#### Sentence length
localhost_3000_applications_7dcfc141-6e9c-443f-9c63-ef6daa5f2ff7_tasks_sentence-information_pages_sentence-length (2)
localhost_3000_applications_7dcfc141-6e9c-443f-9c63-ef6daa5f2ff7_tasks_sentence-information_pages_sentence-length
localhost_3000_applications_7dcfc141-6e9c-443f-9c63-ef6daa5f2ff7_tasks_sentence-information_pages_sentence-length (1)

### Check your answers
localhost_3000_applications_840b47aa-4a6e-4f61-8929-6ca683d3367c_tasks_check-your-answers_pages_review

# Release checklist

[Release process documentation](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/edit-v2/4247847062?draftShareId=a1c360ab-bd31-4db1-aae3-7cc002761de9).

## Pre-merge checklist

- [ ] Are any changes required to dependent services for this change to work?
  (eg. CAS API)
- [ ] Have they been released to production already?

## Post-merge checklist

- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to test
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to preprod
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to prod

### CODE REVIEW

**Comment by bryangaledxw** [comment]
[Remaining sentence info pages](https://trello.com/c/TdhPKLJv/1266-remaining-sentence-info-pages)

**Comment by selina-dxw** [comment]
For the sentence length error message, could it be changed to: 

'The sentence length must be a number, like 2'

Otherwise looks good.

**Comment by bryangaledxw** [comment]
@selina-dxw ✅

**Review by tahb — APPROVED** [review]
LGTM

**Pull request merged**
