### PR TITLE
feat: change arrival date

### PR DESCRIPTION
**Pull request by andrewcharnley**
The story and requirements for this ticket can be found at

https://trello.com/c/g21vPEk8/1638-users-can-change-a-bookings-arrival-date

Note that the requirements are incomplete as the user also needs a means to change the arrival notes. At first I thought new notes were appending but after hitting the endpoint I discovered they are replaced.

# Context

Screenshot 2023-12-01 at 18 36 42
Screenshot 2023-12-01 at 18 37 08
Screenshot 2023-12-01 at 18 37 19

## Pre-merge checklist

- [ ] Are any changes required to dependent services for this change to work?
  (eg. CAS API)
- [ ] Have they been released to production already?

## Post-merge checklist

- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to test
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to preprod
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to prod

### CODE REVIEW

**Comment by richpjames** [comment]
Please can you add some context as to why this change is being made and what the changes are in both the PR description and the commit messages? It would also be helpful to have a link to the Jira ticket

**Comment by andrewcharnley** [comment]
> Please can you add some context as to why this change is being made and what the changes are in both the PR description and the commit messages? It would also be helpful to have a link to the Jira ticket

I added a link to the trello card.

I don't understand how to describe the commits as they appear to be doing exactly as what the title says they are doing, so I'd only be duplicating that. If you could provide a better description for this commit as an example, that would help me understand the ask.

https://github.com/ministryofjustice/hmpps-temporary-accommodation-ui/pull/778/commits/712d8bd6e7751a310ed78ee1a79a582b6241e9f0

**Comment by richpjames** [comment]
Thanks for adding the link to the Trello card. 

The title of each commit doesn't say what they're doing, most of them mention the files that have been touched which is visible from the diff. 
I am trying to understand in the 'integration tests' commit we are skipping the 'New Arrival' tests but without a description of what the commit is trying to achieve it's difficult.  
The [MoJ development principles](https://docs.google.com/document/d/1e-K0apLsBwKWIb5ggPcXTToDinZ7rUVkoto_XBDkyLw/) suggests that commit messages follow [GDS guidance](https://github.com/alphagov/styleguides/blob/master/git.md) which states messages include not only the 'what' but also the 'why' which would make things easier.

**Comment by andrewcharnley** [comment]
> Thanks for adding the link to the Trello card.
> 
> The title of each commit doesn't say what they're doing, most of them mention the files that have been touched which is visible from the diff. I am trying to understand in the 'integration tests' commit we are skipping the 'New Arrival' tests but without a description of what the commit is trying to achieve it's difficult. The [MoJ development principles](https://docs.google.com/document/d/1e-K0apLsBwKWIb5ggPcXTToDinZ7rUVkoto_XBDkyLw/) suggests that commit messages follow [GDS guidance](https://github.com/alphagov/styleguides/blob/master/git.md) which states messages include not only the 'what' but also the 'why' which would make things easier.

There is no why, it's an error and I'm glad you caught it. Just put a comment next to the code.

As I say I'd need an example as I don't understand how to answer 'explain why you are adding a unit test'.

**Comment by tahb** [comment]
Thanks @richpjames, I've rebased the git history in a few places so hopefully this is ready again.

**Review by richpjames — APPROVED** [review]
LGTM, thanks @tahb

**Comment by tahb** [comment]
As it doesn't look like Andrew is working today it seems reasonable for us to merge this where we'd normally wait for the author.

**Pull request merged**
