### PR TITLE
Safeguarding and support section

### PR DESCRIPTION
**Pull request by bryangaledxw**
# Changes in this PR

* Add four new pages for the safeguarding and support section

## Screenshots of UI changes
localhost_3000_applications_3f0414da-416f-4d24-98d8-96c75d6a848b
localhost_3000_applications_3f0414da-416f-4d24-98d8-96c75d6a848b_tasks_safeguarding-and-support_pages_safeguarding-and-vulnerability (1)

localhost_3000_applications_3f0414da-416f-4d24-98d8-96c75d6a848b_tasks_safeguarding-and-support_pages_support-in-the-community
localhost_3000_applications_3f0414da-416f-4d24-98d8-96c75d6a848b_tasks_safeguarding-and-support_pages_local-connections
localhost_3000_applications_3f0414da-416f-4d24-98d8-96c75d6a848b_tasks_safeguarding-and-support_pages_caring-responsibilities
localhost_3000_applications_3f0414da-416f-4d24-98d8-96c75d6a848b_tasks_check-your-answers_pages_review

# Release checklist

[Release process documentation](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/edit-v2/4247847062?draftShareId=a1c360ab-bd31-4db1-aae3-7cc002761de9).

## Pre-merge checklist

- [ ] Are any changes required to dependent services for this change to work?
  (eg. CAS API)
- [ ] Have they been released to production already?

## Post-merge checklist

- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to test
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to preprod
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to prod

### CODE REVIEW

**Comment by bryangaledxw** [comment]
[Safeguarding and support section](https://trello.com/c/2tYA4juZ/1215-safeguarding-and-support-section)

**Comment by bryangaledxw** [comment]
@selina-dxw Couple of additional changes I made:
* On the first screen, the text box has the label "Provide details", with the extra text brought down into the hint text immediately below. This goes against the Figma design, but is consistent with the last screen
* The middle two screens (that are both just text boxes without the y/n question) both now show on the CYA page as "Details of..."
* The answers in CYA will show in the order the user originally entered them, which might go against the expected order given the tab UI - I'll see if I can do anything about this

**Review by tahb — APPROVED** [review]
LGTM

**Comment by selina-dxw** [comment]
Looks good, thanks Bryan. 

On the CYA order, will the 'change' button take the user to the correct question? If so I think it's fine that the answers will appear in the order the user entered.

**Comment by bryangaledxw** [comment]
@selina-dxw Yep, will go to the correct section. And the question ordering in CYA - with the changes I made to fix CYA with branching tasks, they'll always be in the same order as the pages

**Pull request merged**
