### PR TITLE
Update consent and eligibility pages

### PR DESCRIPTION
**Pull request by bryangaledxw**
### Before
localhost_3000_applications_03dffe8a-6b14-499e-a5b6-9b27f2f2f420_tasks_consent_pages_consent-given (1)
localhost_3000_applications_03dffe8a-6b14-499e-a5b6-9b27f2f2f420_tasks_eligibility_pages_eligibility-reason (1)

### After
localhost_3000_applications_03dffe8a-6b14-499e-a5b6-9b27f2f2f420_tasks_consent_pages_consent-given
localhost_3000_applications_03dffe8a-6b14-499e-a5b6-9b27f2f2f420_tasks_eligibility_pages_eligibility-reason

# Release checklist

[Release process documentation](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/edit-v2/4247847062?draftShareId=a1c360ab-bd31-4db1-aae3-7cc002761de9).

## Pre-merge checklist

- [ ] Are any changes required to dependent services for this change to work?
  (eg. CAS API)
- [ ] Have they been released to production already?

## Post-merge checklist

- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to test
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to preprod
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to prod

### CODE REVIEW

**Comment by bryangaledxw** [comment]
[Update consent and eligibility pages](https://trello.com/c/WAXzUQ51/1328-update-consent-and-eligibility-pages)

**Comment by selina-dxw** [comment]
Can the content about an accommodation compact on the consent screen be changed to: 

The person must also sign an Accommodation Compact. See the [operational guidance for TA](https://equip-portal.equip.service.justice.gov.uk/CtrlWebIsapi.dll/?__id=webDiagram.show&map=0%3AFF2D8D3F16B44268B814F7F8177A16F7&dgm=6B8C1C46E26D4ACFBEC3D16F7ABA3029) for more information.

**Comment by bryangaledxw** [comment]
@selina-dxw ✅

**Review by tahb — APPROVED** [review]
LGTM

**Pull request merged**
