### PR TITLE
Remove "formerly" from all mentions of CAS3

### PR DESCRIPTION
**Pull request by bryangaledxw**
# Changes in this PR

Our service sometimes refers to Temporary Accommodation as being "formerly" known as CAS3, despite this being a term in active use. This PR corrects things by removing references to "formerly"

For consistency, this PR also changes instances of "Temporary Accommodation (TA)" to "Temporary Accommodation (CAS3)"  

### Before
localhost_3000_referrals_f242c6ab-92ac-457b-8b97-209ba0b24149_tasks_placement-considerations_pages_accommodation-sharing (1)
localhost_3000_referrals_f242c6ab-92ac-457b-8b97-209ba0b24149_tasks_behaviour-in-cas_pages_previous-stays (1)
localhost_3000_referrals_f242c6ab-92ac-457b-8b97-209ba0b24149_tasks_consent_pages_consent-given (1)

### After
localhost_3000_referrals_f242c6ab-92ac-457b-8b97-209ba0b24149_tasks_placement-considerations_pages_accommodation-sharing
localhost_3000_referrals_f242c6ab-92ac-457b-8b97-209ba0b24149_tasks_behaviour-in-cas_pages_previous-stays (2)
localhost_3000_referrals_f242c6ab-92ac-457b-8b97-209ba0b24149_tasks_consent_pages_consent-given

# Release checklist

[Release process documentation](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/edit-v2/4247847062?draftShareId=a1c360ab-bd31-4db1-aae3-7cc002761de9).

## Pre-merge checklist

- [ ] Are any changes required to dependent services for this change to work?
  (eg. CAS API)
- [ ] Have they been released to production already?

## Post-merge checklist

- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to test
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to preprod
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to prod

### CODE REVIEW

**Comment by bryangaledxw** [comment]
[Remove "formerly" from all mentions of CAS3](https://trello.com/c/wi84HnIq/1456-remove-formerly-from-all-mentions-of-cas3)

**Review by tahb — COMMENTED** [review]
I wonder what we should do about the use of "TA" that we look to still have 8 times now that we've removed referenced to what it stands for. 

- We could switch to using CAS3 but we seem to be using that as more of an 'also known as', so that doesn't feel right to plaster everywhere.
- We could leave it, which seems unhelpful for a new service to introduce TA and leave it to users to figure out
- Perhaps the right thing to do is replace instances of TA with the long form?

**Comment by bryangaledxw** [comment]
@tahb I've removed that second commit after checking with Laura. Think we just want to make the conservative change with this PR

**Review by tahb — APPROVED** [review]
👍

**Pull request merged**
