### PR TITLE
Find a bedspace results include overlapping residents in the same property

### PR DESCRIPTION
**Pull request by bryangaledxw**
# Changes in this PR

This PR builds on #545 and displays residents staying in the property during the searched-for period, with the number of days overlap, and the CRN of the resident

### Before
localhost_3000_find-a-bedspace_startDate-day=1 startDate-month=1 startDate-year=2024 durationDays=84 probationDeliveryUnit=Barnsley+and+Rotherham (1)

### After
localhost_3000_find-a-bedspace_startDate-day=1 startDate-month=1 startDate-year=2024 durationDays=84 probationDeliveryUnit=Barnsley+and+Rotherham

# Release checklist

[Release process documentation](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/edit-v2/4247847062?draftShareId=a1c360ab-bd31-4db1-aae3-7cc002761de9).

## Pre-merge checklist

- [ ] Are any changes required to dependent services for this change to work?
  (eg. CAS API)
- [ ] Have they been released to production already?

## Post-merge checklist

- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to test
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to preprod
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to prod

### CODE REVIEW

**Comment by bryangaledxw** [comment]
[Find a bedspace results include overlapping residents in the same property](https://trello.com/c/2QJRByny/1424-find-a-bedspace-results-include-overlapping-residents-in-the-same-property)

**Comment by bryangaledxw** [comment]
@libuk Converting back to draft until CI passes - need to rebase on top of #571

**Comment by bryangaledxw** [comment]
@libuk Ready for you to take a look

**Review by libuk — APPROVED** [review]
Nice, looks good!

**Pull request merged**
