### PR TITLE
Update Apply section names and contents

### PR DESCRIPTION
**Pull request by bryangaledxw**
# Changes in this PR

* Rename "Provide details of behaviour in previous accommodation" to "Outline behaviour in CAS"
* Move the above task into the risks section
* Rename risks section from "Risk, strength and need information" to "Assess risks for placement"
* Rename "Required referrals and documents" to "Required referrals"

### Before
localhost_3000_referrals_857faab4-5190-4caa-b2e7-70a8ccec32e1

### After
localhost_3000_referrals_b5b5ffbf-a785-48fd-9cb4-a2b6765daaf3

# Release checklist

[Release process documentation](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/edit-v2/4247847062?draftShareId=a1c360ab-bd31-4db1-aae3-7cc002761de9).

## Pre-merge checklist

- [ ] Are any changes required to dependent services for this change to work?
  (eg. CAS API)
- [ ] Have they been released to production already?

## Post-merge checklist

- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to test
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to preprod
- [ ] [Manually approve](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4247847062/Release+process#Manual-releases)
  release to prod

### CODE REVIEW

**Comment by bryangaledxw** [comment]
@selina-dxw Any idea what we want to do here?
image

Is there shorter text we can use, and do we want "behaviour in previous accommodation" to come below any of the existing tasks?

Apologies I didn't spot the text issue before, was looking at the form with all sections completed, where it all fits on one line!

**Comment by selina-dxw** [comment]
Can we change the title to 'Outline behaviour in CAS', and then move it to the bottom of the list in risks I reckon.

**Comment by bryangaledxw** [comment]
@selina-dxw ✅

**Comment by bryangaledxw** [comment]
[Update Apply section names and contents](https://trello.com/c/8i7tHqRP/1327-update-apply-section-names-and-contents)

**Review by tahb — APPROVED** [review]
LGTM

**Pull request merged**
